name: flutter_device_separator
description: A new Flutter package project.
version: 1.0.0
homepage: https://github.com/idonuntius/flutter_device_separator

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
